---
collections:
        - name: vmware.vmware_rest
        - name: community.vmware
          version: 3.4.0
        - name: community.general
        - name: ansible.posix
        - name: community.sap_libs
        - name: community.sap_operations
        - name: community.sap_install
        - name: https://github.com/sap-linuxlab/community.sap_launchpad.git
          type: git
